apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortener
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: url-shortener
  template:
    metadata:
      labels:
        app: url-shortener
    spec:
      containers:
        - name: url-shortener
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.env.SERVER_PORT | int }}
          env:
            - name: SERVER_PORT
              value: "{{ .Values.env.SERVER_PORT }}"
            - name: POSTGRES_DB_URL
              value: "{{ .Values.env.POSTGRES_DB_URL }}"
            - name: POSTGRES_DB_USERNAME
              value: "{{ .Values.env.POSTGRES_DB_USERNAME }}"
            - name: POSTGRES_DB_PASSWORD
              value: "{{ .Values.env.POSTGRES_DB_PASSWORD }}"
---
apiVersion: v1
kind: Service
metadata:
  name: url-shortener-service
spec:
  selector:
    app: url-shortener
  ports:
    - port: 80
      targetPort: {{ .Values.env.SERVER_PORT | int }}
  type: NodePort