name: CI

on:
  push:
    branches:
      - '**'

  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      SERVER_PORT: 8080

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Lint code with Spotless
        run: ./gradlew spotlessCheck

      - name: Run tests with debug info
        run: ./gradlew test --stacktrace --info

      - name: Generate coverage report
        run: ./gradlew jacocoTestReport

      - name: Upload coverage report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: build/reports/jacoco/test/html/

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:0.1.0 .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/url-shortener:0.1.0
